version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: djangopass
      POSTGRES_DB: djangodb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
